# 데이터 시각화

seaborn 패키지를 활용하여 데이터 시각화 실습을 수행한다.

먼저 필요한 데이터를 로드한다.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt

# seaborn 임포트
import seaborn as sns

%matplotlib inline

In [ ]:
tips = sns.load_dataset('tips')
titanic = sns.load_dataset('titanic')
iris = sns.load_dataset('iris')

문제 1. 

tips['total_bill']에 대한 히스토그램을 그리시오.

문제 2.

tips 데이터프레임에서 요일별 데이터의 빈도(frequency) 막대그래프로 표시하시오.

문제 3.

titanic 데이터 셋 - 타이타닉호의 각 클래스별 승객 수를 막대그래프로 표시하시오.

문제 4.

titanic 데이터 셋 - 타이타닉호의 생존자와 사망자의 명 수를 막대그래프로 비교해서 나타내시오.

문제 5. 

tips 데이터셋 - 'total_bill'과 'tip'의 상관관계를 산점도로 나타내시오.

문제 6.

tips 데이터셋 - 'time'가 Lunch, Dinner에 따라서 'total_bill'분포를 비교하는 박스 그래프를 표시하시오.

문제 7.

iris 데이터 셋 - sepal_length	sepal_width	petal_length	petal_width의 상관관계 쌍을 산점도 행렬을 그려서 나타내시오.